### ISSUE TITLE
Standardize "origin"

### ISSUE THREAD

**Issue by peterdesmet** [inbo/alien-species-checklist#53]
Please use https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 as much as possible

**Comment by timadriaens** [comment]
field term: native range, to discriminate between natural range expansion and alien is important, and we don’t want to lose the information on where they naturally occur e.g. species where it is unknown whether they had natural range expansion or were introduced. Therefore, we can have EU in the area of origin (e.g. pontocaspian species, central european spp).

we don’t follow the gisin terms here since they are in our opinion status

there seems to be no corresponding controlled vocabulary in GRIIS for origin

we therefore mapped onto the NOBANIS technical manual terms 

idea is to link origin with status and to distinguish primarily between species native to other parts of the EU from species from other continents

**Comment by timadriaens** [comment]
so our field values are:

Continents
Africa The African continent
Antarctica The Antarctic continent
Asia Divides Asia from Europe along Ural/Kazakhstan, Black Sea
Europe Divides Europe from Asia along Ural/Kazakhstan
N. America Canada, USA and Mexico
Oceania Australia, New Zealand, Tasmania and a number of small islands
S. America All countries on the S. American continent south of Mexico

Oceans
Arctic Ocean The ocean surrounding the North Pole
Indian Ocean The Ocean south of India to the southern tip of Africa and to the northern tip of Australia
N. Atlantic Ocean Upper part of the Atlantic Ocean divided by the equator
S. Atlantic Ocean The lower part of the Atlantic Ocean divided by the equator
N. Pacific Ocean The upper part of the Pacific Ocean divided by the equator
S. Pacific Ocean The lower part of the Pacific ocean divided by the equator
Southern Oceans The ocean surrounding the South Pole
combinations (also across continents | oceans)
