### ISSUE TITLE
Should we include "to be determined by experts" and "unknown" in the vocabs

### ISSUE THREAD

**Issue by peterdesmet** [inbo/alien-species-checklist#63]
Several mappings use the terms "to be determined by experts" and/or "unknown". @timadriaens are these intermediate values or values that should be part of the controlled vocabulary? Can you indicate below:

## For "unknown"

Note: GBIF often uses "uncertain" as alternative for "unknown".

* [x] Include in `introductionPathway`?
* [x] Include in `invasionStage`?
* [x] Include in `nativeRange`?
* [x] Include in `presence`?

## For "to be determined by experts"

* [ ] Include in `habitat`? (there's also `to be determined by experts, primarily marine probably`)
* [ ] Include in `introductionPathway`?
* [ ] Include in `invasionStage`?
* [ ] Include in `presence`?

**Comment by timadriaens** [comment]
to be determined by experts = this means we want to go back to the original data providers and ask them to fill in this field with the appropriate mapped terms because they represent new data or because filling those requires interpretation that we cannot do alone. So it means we will be sending them emails with spreadsheets. Hopefully, they are going to be willing to update their own datasets with these extra field and they will see the added value of using standardized terms.

**Comment by timadriaens** [comment]
unknown = it is really not known (=it would require new knowledge to fill this). In our opinion, this is not the same as 'uncertain' because uncertain implies you have an idea but are not sure. So uncertain is a notion of confidence, not a field value. In fact, when we determine pathways for instance, it is advised to put a confidence on that assessment, but for our purpose now that is a little bit overkill.

**Comment by SoVDH** [comment]
**Attention** : "To be determined by experts"  is not a controlled vocabulary and **should not** appear in the checklist though it should be kept for us as a next step to proceed. This mean in the final checklist, this should result in an **empty cell** !!!

On the contrary, "unknown" is really an item and should appear in the checklist.

**Comment by peterdesmet** [comment]
Ok, will add unknown, but not to be determined.

Know that if providers give you new data, we won't be able to include it automatically in the finalized checklist: the repeatable chain has been long broken, so it needs to be updated manually. That's what our paper is about too. 😄

**Comment by peterdesmet** [comment]
Done in 4fb29446f0d7c9be07f8436bbcaa47ae0975cc52
